services:
  order-mariadb:
    image: mariadb:11.3
    container_name: order-mariadb
    restart: unless-stopped
    ports:
      - "9001:3306"
    volumes:
      - order-mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "some-password"
      MYSQL_DATABASE: "orders"
      MYSQL_USER: "orders"
      MYSQL_PASSWORD: "another-password"

  order-pma:
    image: phpmyadmin
    container_name: order-pma
    restart: unless-stopped
    ports:
      - "9002:80"
    environment:
      PMA_HOST: "order-mariadb"
      PMA_USER: "root"
      PMA_PASSWORD: "some-password"

volumes:
  order-mariadb:
